import { Vehicle, Staff } from '../../domain/types';
import { VehicleStatus } from '../../domain/constants';

export const createMockVehicle = (overrides: Partial<Vehicle> = {}): Vehicle => ({
  id: Math.floor(Math.random() * 1000),
  code: 'VH-0001',
  name: 'Test Vehicle',
  year: '2020',
  status: VehicleStatus.IN_STOCK,
  purchase_price: 100000000,
  purchase_date: '2024-01-01',
  buyer: 'ADMIN',
  buyer_name: 'Admin',
  customer_name: '',
  sale_price: 0,
  sale_date: '',
  seller: '',
  seller_name: '',
  commission: 0,
  buying_commission: 3000000,
  buying_bonus: 0,
  buying_bonus_paid: false,
  total_cost: 0,
  cost_history: [],
  is_pinned: false,
  is_coinvested: false,
  coinvestor_code: '',
  coinvest_amount: 0,
  image_url: '',
  images: [],
  notes: '',
  purchase_paid_amount: 0,
  purchase_payment_history: [],
  received_amount: 0,
  sale_payment_history: [],
  history: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  odo: 0,
  color: 'White',
  profit: 0,
  days: 0,
  partner_capital_repaid: false,
  partner_profit_shared: false,
  ...overrides
});

export const createMockStaff = (overrides: Partial<Staff> = {}): Staff => ({
  id: Math.floor(Math.random() * 1000),
  code: 'NV01',
  name: 'Nguyen Van A',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  base_salary: 10000000,
  target: 5,
  commission_per_car: 500000,
  role: 'SALES',
  department: 'Sales',
  status: 'ACTIVE',
  email: 'test@example.com',
  phone: '0123456789',
  expenses: [],
  paid_months: [],
  password_hash: null,
  auth_id: null,
  ...overrides
});
