/**
 * Application Constants
 */

export const CURRENCY = {
  BILLION: 1_000_000_000,
  MILLION: 1_000_000,
  THOUSAND: 1_000,
};

export const STAFF = {
  DEFAULT_BUYING_COMMISSION: 3_000_000,
  DEFAULT_SALE_COMMISSION: 5_000_000,
  BONUS_THRESHOLD_PERCENT: 70,
  BONUS_MULTIPLIER_FULL: 1,
  BONUS_MULTIPLIER_REDUCED: 0.7,
};

export const INVENTORY = {
  AGING_THRESHOLD_DAYS: 25,
};



export { PERMISSIONS, ROLE_PERMISSIONS } from './modules/auth/domain/PermissionService';


export const Z_INDEX = {
  BASE: 0,
  DRAWER: 40,
  HEADER: 50,
  MODAL_BACKDROP: 9998,
  MODAL: 9999,
  TOAST: 10000,
};
