/**
 * Application Constants
 */

export const CURRENCY = {
  BILLION: 1_000_000_000,
  MILLION: 1_000_000,
  THOUSAND: 1_000,
};

export const STAFF = {
  DEFAULT_BUYING_COMMISSION: 3_000_000,
  DEFAULT_SALE_COMMISSION: 5_000_000,
  BONUS_THRESHOLD_PERCENT: 70,
  BONUS_MULTIPLIER_FULL: 1,
  BONUS_MULTIPLIER_REDUCED: 0.7,
};

export const INVENTORY = {
  AGING_THRESHOLD_DAYS: 25,
};



export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  EDIT_INVENTORY: 'EDIT_INVENTORY',
  VIEW_CASHFLOW: 'VIEW_CASHFLOW',
  EDIT_CASHFLOW: 'EDIT_CASHFLOW',
  VIEW_STAFF: 'VIEW_STAFF',
  EDIT_STAFF: 'EDIT_STAFF',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_PERSONAL: 'VIEW_PERSONAL',
  VIEW_TEAM_DATA: 'VIEW_TEAM_DATA',
  VIEW_OWN_DATA_ONLY: 'VIEW_OWN_DATA_ONLY',
};

import { UserRole } from './shared/domain/constants';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [UserRole.ADMIN]: Object.values(PERMISSIONS),
  [UserRole.ACCOUNTANT]: [
    PERMISSIONS.VIEW_PERSONAL,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.EDIT_INVENTORY,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.EDIT_STAFF,
    PERMISSIONS.VIEW_CASHFLOW,
    PERMISSIONS.EDIT_CASHFLOW,
  ],
  [UserRole.MANAGER]: [
    PERMISSIONS.VIEW_PERSONAL,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.VIEW_CASHFLOW,
  ],
  [UserRole.STAFF]: [
    PERMISSIONS.VIEW_PERSONAL,
    PERMISSIONS.VIEW_INVENTORY,
  ],
  [UserRole.SALES_LEADER]: [
    PERMISSIONS.VIEW_PERSONAL,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_TEAM_DATA,
  ],
  [UserRole.SALES_STAFF]: [
    PERMISSIONS.VIEW_PERSONAL,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_OWN_DATA_ONLY,
  ],
};


export const Z_INDEX = {
  BASE: 0,
  DRAWER: 40,
  HEADER: 50,
  MODAL_BACKDROP: 9998,
  MODAL: 9999,
  TOAST: 10000,
};
